package com.offboardingMS.demo.model;

public enum Status {
	NOTIFY_MANAGEMENT,
	SCHEDULE_EXIT_INTERVIEW,
	KNOWLEDGE_TRANSFER,
	REVOKE_COMPANY_ACCESS,
	RETRIEVE_COMPANY_PROPERTY,
	CONDUCT_EXIT_INTERVIEW,
	NOTIFIY_ALL_EMPLOYEE,
	UPDATE_HR_RECORDS,
	PROCESS_COMPLETED_THANKS,
}
